name: Run Web Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed
  push:
    branches:
      - master

jobs:
  webscrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Download ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

    - name: Run web scraper
      run: |
        python web_scrapecode.py
      env:
        DISPLAY: ":99"  # Necessary for headless Chrome
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

